# Generated by Django 3.1.4 on 2020-12-08 08:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.DecimalField(decimal_places=0, default=None, max_digits=15)),
                ('role', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_authorization', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('company_legal_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('private_label', models.CharField(max_length=100)),
                ('state_of_formation', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', django.contrib.postgres.fields.jsonb.JSONField()),
                ('zip_code', models.CharField(max_length=100)),
                ('which_market', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sel_fulfillment_countries', django.contrib.postgres.fields.jsonb.JSONField()),
                ('product_count', django.contrib.postgres.fields.jsonb.JSONField()),
                ('annual_total_revenue', django.contrib.postgres.fields.jsonb.JSONField()),
                ('online_selling', django.contrib.postgres.fields.jsonb.JSONField()),
                ('commercial_product', django.contrib.postgres.fields.jsonb.JSONField()),
                ('seller_type', django.contrib.postgres.fields.jsonb.JSONField()),
                ('how_got_site', django.contrib.postgres.fields.jsonb.JSONField()),
                ('note', models.TextField()),
                ('dropship', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('product_liability_insurance', models.DecimalField(decimal_places=0, max_digits=1)),
                ('product_categories', django.contrib.postgres.fields.jsonb.JSONField()),
                ('accept_return', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
            ],
        ),
    ]
