# Generated by Django 3.1.4 on 2021-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20210127_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='accept_return',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_line1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_line2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='annual_total_revenue',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commercial_product',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_legal_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='dropship',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='how_got_site',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_authorization',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='online_selling',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='private_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='product_categories',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='product_count',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='product_liability_insurance',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='role',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='sel_fulfillment_countries',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='seller_type',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state_of_formation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='which_market',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='zip_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
